services:
  api:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=sqlite:///instance/dev.db
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
    volumes:
      - ./instance:/app/instance
    depends_on:
      - redis

  worker:
    build: .
    env_file:
      - .env
    environment:
      - DATABASE_URL=sqlite:///instance/dev.db
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
    command: celery -A app.tasks worker --loglevel=info
    volumes:
      - ./instance:/app/instance
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
